# config.yaml

project_name: "Dognoise"

# 串口池：给每个串口起个名字，方便代码里调用
serials:
  # 名字: {参数}
  nano:
    port: "COM5"
    baudrate: 9600
    timeout: 1

  esp32_logger:
    port: "COM5"
    baudrate: 115200
    timeout: 2

# ADB设备池
adb_devices:
  main_phone: "10ADBA2S4X001G1"

feishu:
  # Webhook 地址
  webhook: "https://open.feishu.cn/open-apis/bot/v2/hook/e162c2e1-d3b6-4211-9a23-58ff22c76986"
  # (可选) 如果开启了加签安全验证，填入你的 SEC 开头的密钥
  secret: "EPuMiGBOmThcycY0OlzsDh"